import os
import pandas as pd
import numpy as np
import ta

def preprocess_data(input_path="data/raw/gold_prices.csv", output_path="data/processed/gold_processed.csv"):
    """
    Cleans raw gold prices and generates technical indicators for Machine Learning.
    """
    if not os.path.exists(input_path):
        print(f"Error: Raw data file {input_path} not found.")
        return
        
    print(f"Loading raw data from {input_path}...")
    df = pd.read_csv(input_path)
    df['Date'] = pd.to_datetime(df['Date'])
    df.sort_values('Date', inplace=True)
    df.set_index('Date', inplace=True)
    
    # Handle missing values
    df.ffill(inplace=True)
    
    print("Generating technical indicators...")
    # Add Moving Averages
    df['SMA_10'] = ta.trend.sma_indicator(df['Close'], window=10)
    df['SMA_50'] = ta.trend.sma_indicator(df['Close'], window=50)
    df['EMA_20'] = ta.trend.ema_indicator(df['Close'], window=20)
    
    # Momentum Indicators
    df['RSI'] = ta.momentum.rsi(df['Close'], window=14)
    df['MACD'] = ta.trend.macd(df['Close'])
    df['MACD_Signal'] = ta.trend.macd_signal(df['Close'])
    
    # Volatility
    df['Bollinger_High'] = ta.volatility.bollinger_hband(df['Close'])
    df['Bollinger_Low'] = ta.volatility.bollinger_lband(df['Close'])
    
    # Daily Returns & Volatility
    df['Daily_Return'] = df['Close'].pct_change()
    df['Volatility_20'] = df['Daily_Return'].rolling(window=20).std()
    
    # Target Variable: Next Day's Close Price (Shifted -1)
    df['Target_Next_Close'] = df['Close'].shift(-1)
    
    # Drop NaNs that were generated by indicators or shifting
    df.dropna(inplace=True)
    
    # Reset index to save Date as column
    df.reset_index(inplace=True)
    
    # Create directory if it doesn't exist
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    df.to_csv(output_path, index=False)
    print(f"Processed dataset saved to {output_path} ({len(df)} rows)")

if __name__ == "__main__":
    preprocess_data()
